# See: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#usage-with-pull-requests-from-public-forked-repositories
name: Dependency review

on:
  pull_request:

# Configure GitHub Actions cancel in progress workflow to avoid redundant runs in same branch.
# See: https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.event_name == 'pull_request' && github.head_ref || 'master-group' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dependency review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
